### ISSUE TITLE
Exception occurs when mouse cursor disappears

### ISSUE THREAD

**Issue by samielatri** [PaysPlat/DesktopSbS#12]
Hi ! Thank you for this amazing work, this software was really useful for me.

Exception occurs when mouse cursor disappears

[exception.txt](https://github.com/PaysPlat/DesktopSbS/files/6397061/exception.txt)

**Comment by PaysPlat** [comment]
Hi,

Regarding the exception details, it seems there is an issue when application try to read settings file.
Can you look for settings file `user.config`
in folder `%localappdata%\PaysPlat\DesktopSbS.exe_Url_<xxxxxxxxxxxxxxxxxxxx>\1.2.0.0\`

and send it to me ?

You can also make a try by suppressing it and test again DesktopSbS.

PaysPlat

**Comment by samielatri** [comment]
Hey,
Thank you for your reponse.

I fixed the problem when i resetted my mouse cursor's options in windows 10.

I don't think the settings file will be useful after the reset but i sent it here (extension was modified to be txt as github won't accept config files).
 
Actually, the mouse cursor, suddenly, disappeared and i had that excpetion but it might have nothing to do with desktopSBS.

Have a nice day.

[user.config.txt](https://github.com/PaysPlat/DesktopSbS/files/6429784/user.config.txt)

**Comment by PaysPlat** [comment]
Hello,

> Actually, the mouse cursor, suddenly, disappeared and i had that excpetion but it might have nothing to do with desktopSBS.

It is normal behaviour of DesktopSbS to hide mouse cursor.
Cursor is replaced by 2 cursor images on each sub-screen.
And Windows mouse cursor is restored when DesktopSbS closes...

Except if there is an exception and DesktopSbS crashes,
maybe I will try in a future release to restore it anyways.

So the mouse cursor disappearance is a consequence of exception :).

The configuration file you have provided seems OK,
is DesktopSbS work correctly now ?

Regards

PaysPlat

**Comment by samielatri** [comment]
Hey again,

Yes, it works perfectly fine. 

Thank you :) 

Have a nice day.
