### ISSUE TITLE
request : barrel distortion and others

### ISSUE THREAD

**Issue by catzy007** [PaysPlat/DesktopSbS#2]
please, can you add barrel distortion and analygraph filter.. i trying to make something similar to this and still not working properly. you can get some reference from https://archive.codeplex.com/?p=vrplayer

thanks before

**Comment by PaysPlat** [comment]
Hi,

Due to Windows DWM technology I use for rendering, it is not possible to manage distortion as you want.

I'm sorry.

PaysPlat
