### ISSUE TITLE
HTC Vive: Retained aspect ratio option? Graphical glitch and several mouse cursor issues.

### ISSUE THREAD

**Issue by Roy2D2C** [PaysPlat/DesktopSbS#3]
1. When I run DesktopSBS it sets the vive to SBS and the monitor to normal. Testing different resolution combinations changed the focal point on the headset. I would compare it to having a monitor and your 3dtv connected at the same time. but the 3dtv looks squished horizontally. I asked around and this is the response I got: 

"SBS usually compresses the images in the pair to still fit inside the same frame as a single image. That is why you are getting the image squashed sideways in your headset. A proper image here would be SBS but with retained aspect ratio.  it will show up squashed as long as you have standard SBS mode. Screen halves need to keep aspect ratio to display properly in the headset."

![hmd example](https://user-images.githubusercontent.com/42761557/44703229-b6be6400-aa4b-11e8-9256-9980ed1605bb.jpg)
![monitor example](https://user-images.githubusercontent.com/42761557/44703235-bb831800-aa4b-11e8-96f5-d198ca0778f5.jpg)

2. Noticed an issue un-docking and when un-maximizing the window from the non sbs monitor.

![docking example](https://user-images.githubusercontent.com/42761557/44703285-e53c3f00-aa4b-11e8-9abe-33ca85b18fa6.jpg)

3. See the mouse cursor over the window when using an xbox 360 controller.
4. Also see the windows cursor off to the side of the in game cursor.
5. Mouse cursor changes to an odd plus sign shaped cursor and back randomly.

Will list any more if I find them.
Edited.

**Comment by PaysPlat** [comment]
Hi, I have just released DesktopSbS v0.5 with the 2 new features you have asked for.
[DesktopSbS_v0.5_Setup](https://github.com/PaysPlat/DesktopSbS/releases/download/v0.5/DesktopSbS_v0.5_Setup.exe)
Please have a try and make feedback if needed.

**Comment by Roy2D2C** [comment]
Hello, everything works great. Thank you very much.
