### ISSUE TITLE
Request: Display Case 2

### ISSUE THREAD

**Issue by Roy2D2C** [PaysPlat/DesktopSbS#5]
We talked about a Case 2 before? Display 1(Non-SBS) copied on Display 2(SBS). Can it work with Display 2 not extended or cloned with Windows 10? I think this setup will work better.

**Comment by PaysPlat** [comment]
Hi,

With the current version of DesktopSbS,
You can modify display of one screen to make it SbS : Display 1 => Display
1 SbS.
If you are in extended display, you can choose which display you want to
make SbS : Display N => Display N SbS.
If you are in cloned mode, normally the SbS display is displayed on the 2
screeens.

If you want, in extended mode, make display 1 => Display 2 SbS, I have to
manage it.
I have to find a second screen to dev and test it :).

See you

PaysPlat

**Comment by Roy2D2C** [comment]
Thank you very much for your reply. I can't wait to try out this other mode.

Take care,
Roy

**Comment by Roy2D2C** [comment]
extended mode, make display 1 => Display 2 SbS
Yes, please :)

**Comment by PaysPlat** [comment]
Hi,

I have released DesktopSbS v1.0,
you can now manage source screen and destination screen as you want.
All settings are configurable in Settings window.

Bye 

PaysPlat
