### ISSUE TITLE
Double-width desktop with maintained aspect ratio

### ISSUE THREAD

**Issue by kevin-dimenco** [PaysPlat/DesktopSbS#6]
I have a double-width 3d monitor (x resolution is doubled), meaning my left eye sees the left half of the desktop and my right eye sees the right half. It looks terrible. This project could really be a solution.

This is my desktop without DesktopSbS:
![1](https://user-images.githubusercontent.com/43068132/50146814-ef14d700-02b4-11e9-8b9c-5ea479de47f4.png)

However, when I run DesktopSbS, I basically have to choose between
1. Turning KeepAspectRatio off and everything looks squished

![2](https://user-images.githubusercontent.com/43068132/50146903-21becf80-02b5-11e9-8616-3a3ad4f98087.png)

2. Or turning it on and having a screen that is 50% black

![3](https://user-images.githubusercontent.com/43068132/50146938-33a07280-02b5-11e9-9d40-26f12bbc7c16.png)

I think my solution would be to make everything 50% smaller like with KeepAspectRatio true, *except* for the background, and for the task bar to be in the correct Y position. Then I would be rid of the black bars.
![4](https://user-images.githubusercontent.com/43068132/50147257-f38dbf80-02b5-11e9-8c93-1652e7000d01.png)

Do you have any ideas on how to get a good-looking desktop on my 3d monitor?

**Comment by PaysPlat** [comment]
Hi,

I think about 2 possibilities:

1) like your proposition : 50% smaller with keep aspect ratio but with respect to full Y position. you will lost details on windows and some strange behaviour with mouse moves (Y moves will be 2x quicker than X)

2) 100 % size with keep aspect ratio, and we will take only left part of screen as source. It should look great but windows on right side of screen will be invisible.

Can you give me details about your screen (reference) and the settings offered by graphical driver ?

**Comment by kevin-dimenco** [comment]
The screen is a double-4K (7680 x 2160) and expects a side-by-side image in that resolution, i.e. two SBS 4K images (3840 x 2160). It presents itself as 7680x2160 to Windows, which is why the desktop is too wide (the desktop spans both images). The graphical driver doesn't do any 3D processing, nothing special going on there.

**Comment by PaysPlat** [comment]
Hi,
I will have some time during this Christmas holidays,
I will try to propose you a new release soon.

Bye

PaysPlat

Le mer. 19 déc. 2018 à 08:40, kevin-dimenco <notifications@github.com> a
écrit :

**Comment by PaysPlat** [comment]
Hi,
I have released DesktopSbS v1.0.

In this version you can configure a custom source area.
So if you uncheck fullscreen and set width to half your screen width, you can obtain that you want.

Bye

PaysPlat
