### ISSUE TITLE
VR with DesktopSBS

### ISSUE THREAD

**Issue by Roy2D2C** [PaysPlat/DesktopSbS#7]
Video of how I am using DesktopSBS https://www.twitch.tv/videos/356748069 What is the box that pops up at 4:20 in the video? I am using a 360 controller to play the game.

**Comment by PaysPlat** [comment]
Hi,
DesktopSbS analyses continuously all running windows to check if it has to
display them or not.
Maybe there is in an issue with the conditions.

Can you reproduce it easily or it happens random ?

You can find on GitHub repo the DesktopSbS diagnostic tool, it will
generate a report listing windows selected and discarded. You can send me
the report if you succeed to reproduce it.

FYI, I am working to release soon a new version with choice of source and
dest screen, ability to capture only a part of source screen, and graphical
edition of settings.

Bye

PaysPlat

**Comment by Roy2D2C** [comment]
It does it randomly. I have only seen that box twice. thank you for the
info. Looking forward to the next release.

Roy
