### ISSUE TITLE
Solved: Crash on Windows 10 1909 x64

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [PaysPlat/DesktopSbS#8]
After click on "Close", no background process kept in background, and even if not click on "Close",  
all keyboard shortcut not work.  
Sometimes the mouse pointer were gone until a reboot.

The "remember choice" also have no effect and reset to not selected after a software re-run.

**Comment by PaysPlat** [comment]
Hello,
I'm still with Windows 10 1903 for the moment, I will update and test soon.

Did you use DesktopSbS on your computer before Windows update ? And did it
work correctly ?

Thanks

PaysPlat


Le ven. 13 déc. 2019 à 14:29, mhtvsSFrpHdE <notifications@github.com> a
écrit :

**Comment by mhtvsSFrpHdE** [comment]
@PaysPlat So I then grab a Windows 1903 Virtual Machine to test, I have VMWare.  
Windows recently did do many break change between big version...  
If 1903 can work I'm not urgent to request 1909 support, I just do watch some online videos.

**Comment by mhtvsSFrpHdE** [comment]
Also I will heavy use this tool in future...VR can prove much bigger virtual screen than my 24 inch.  
I do programming too,  
If you are able to share some enough knowledge like what pdf book files, technical Information did you use during create the software for a fast bootstrap, I glad to try some necessary patch for compatible contribute on my free time.

**Comment by mhtvsSFrpHdE** [comment]
@PaysPlat It work on 1903, I then can enjoy my virtual screen! Very thanks!

**Comment by PaysPlat** [comment]
Hi, I have updated today to Windows 10 1909 and DesktopSbS works correctly.
If you retry on Windows 1909 and still have issue, you can run DesktopSbs diagnostic application (in same folder) and send me the diagnostic file.

Concerning technical knowledge, DesktopSbS uses Microsoft DWM API, it's the service which display thumbnails of open applications when you hover apps on Windows task bar. So you can read documentation about this service.
For each change, there are several steps : 
- Windows detection : I use User32.EnumWindows() to find all open windows and I filter them regarding their state and locations
- I create blank windows to host DWM displays
- I compute location, crop, size of display area regarding options : horizontal or vertical, keep ratio, parallax effect.
- I apply DWM thumbnails respecting computed parameters.
- I hide mouse cursor and I display fake cursors respecting computed parameters.

It is quite simple, but it takes a lot and a lot tries to make it work correctly :).

If you want to go in depth in code, I can be available to answer your questions.

Merry Xmas.

PaysPlat

**Comment by mhtvsSFrpHdE** [comment]
@PaysPlat It work confirmed on 1909.

I just always imagine a dream one day I found a error in software,  
I can then make a pull request to fix it, to help others instead of submit a issue for asking help...

**Comment by mhtvsSFrpHdE** [comment]
@PaysPlat That was really strange that it work on all my VMware virtual machine, and a Windows 10 Enterprise 1909, but my home PC Windows 10 1909 pro have not work

Here is the log collected from VMware which is can work
```
Removed, issue identified
```

And here is the log from not work home PC
```
Removed, issue identified
```

They are both 1909 and even same 10.0.18363.535

**Comment by mhtvsSFrpHdE** [comment]
@PaysPlat I see ???????? in the log,  
this can mean something is error during scan Window title  
so I made test

it can work on ANSI 936 (Simplified Chinese) Enterprise 1909
it can work on ANSI 936 VMware Pro 1909
but also work on ANSI 1252 (English US) Pro 1909 when a Simplified Chinese title out there

That means not a Encoding error.  
then some random GUI click, I found when click on "DesktopSBS Settings\Screen source Id"  
the software crashed on my home PC, but not crash inside Virtual Machine and Enterprise.

Update: This behavior will trigger a d3d draw

**Comment by mhtvsSFrpHdE** [comment]
@PaysPlat Refer to 
https://github.com/0xd4d/dnSpy/issues/1272

When I try to start debugger and even the debugger is crashed.  
That's pretty cool. And then they have confirmed the `MSI Afterburner`  
and its on-screen layout caused the crash.  
I don't ask a fix then, DesktopSBS has nothing to do with it.  
I just disable MSI Afterburner as fast solution, now everything is fine as expected.  
You can tell other users or put a compatible warning on website around Download button...  
Because other on-screen layout that hijack d3d dll can also have such compatible error.  
Nvidia, Steam, Uplay, etc.
